.github/workflows/ci.yml

We don't want to trigger Percy job on `ember-learn` account. 
Only the CI job is commented, all the other references to Percy are still there, so we could easily keep this setup and use another token.

CI/ remove ember-learn token and comment percy job

---

guides/release/getting-started/working-with-html-css-and-javascript.md
node-tests/helpers/getNonRelativeGuidesLinks.js

A relative link of the guide where pointing to an older version we don't have in the French guide. We redirect to the right page of the English guide instead.

Fix/ Link to a previous version links to the english guide

---

.local.dic
LISEZMOI.md
README.md

Closes #3 
Update `README.md` to fit `ember-fr-guides-source`.
As the purpose of the project is to translate the Ember Guides, let's translate the `README.md` to `LISEZMOI.md`. A few English words that should not be translated have been added to the local dictionary.

Docs/ update and translate `README.md`

---

CONTRIBUTING.md

Closes #7 
CONTRIBUTING.md now fits `ember-fr-guides-source` \o/
(At contrary of the README, this markdown won't be translated as it targets contributors who can translate from English to French)

Docs/ adapt the contributing guide to fit the project

---

node-tests/helpers/getNonRelativeGuidesLinks.js

Yes the RegExp is verbose, but we won't update every day (will we ever actually?).
I could have gone with a more readable `new RegExp(...split group on multiple lines...)` but I don't see the need:
- we know what we want to match
- and the commit's body already provides [help and examples](https://regex101.com/r/vkijKf/1/) to understand the RegExp
1. In the original code, the unescaped `.` was an error.
An unescaped `.` means "any single character", which was incorrect.
What we want is to match the literal `.`, so it needs to be escaped.
2. New and suggested RegExp from https://semver.org
> Is there a suggested regular expression (RegEx) to check a SemVer
> string?
>
> There are two. One with named groups for those systems that support
> them (PCRE [Perl Compatible Regular Expressions, …

fix: fix RegExp for matching SemVer

---

guides/release/getting-started/anatomy-of-an-ember-app.md

Translate .../getting-started/anatomy-of-an-ember-app.md

---

.remarkignore
.remarkrc.mjs
guides/release/accessibility/learning-resources.md
package-lock.json
package.json

As part of  #169, we followed the suggestion in [retextjs/discussions/89](https://github.com/orgs/retextjs/discussions/89) and we installed [remark-message-control ](https://github.com/remarkjs/remark-message-control) to build a linter rule that will ignore the spelling for the next block or the current line.
In practice, `` should be used to ignore complete article titles that we decided to let in English. If a French sentence contains a technical word or English word that is commonly used in French, we should rather add it to the local dictionary.

Spell linter

---

.githooks/pre-commit

This PR shares the first version of a git hook to remember adding the translation file modified in the commit to `.remarkignore`. An issue will be opened to improve it. Closes #169
git >= 2.9
- Run `git config core.hooksPath .githooks`
git < 2.9
- Copy the hook in `.githooks/` to `.git/hooks/`

Share pre-commit hook warning about missing file to lint

---

.local.dic
.remarkignore
.remarkrc.mjs
guides/release/getting-started/working-with-html-css-and-javascript.md

Closes #177 
`retext-repeated-words` is useful in a lot of situations, but in French there are a couple of cases where repeated words are actually expected, especially when using pronominal verbs (nous nous, vous vous). 
Considering we do use this kind of phrasing in the guide, `retext-repeated-words` has been added as a possible source for ``, so it can still lint mistakes but we can deactivate it when the repetition is correct.

Translate/ guides/release/getting-started/working-with-html-css-js

---

app/styles/app.scss
package-lock.json
package.json

This PR replaces `guidemaker-default-template` with `guidemaker-ember-locale-template` to get Zoey informational boxes displayed correctly. Closes #182
[`guidemaker-ember-locale-template`](https://github.com/DazzlingFugu/guidemaker-ember-locale-template) is a new fork of [`guidemaker-default-template`](https://github.com/empress/guidemaker-default-template). We should think of it as a generic alternative Ember template for translation projects like this one.
[`guidemaker-ember-locale-template#1`](https://github.com/DazzlingFugu/guidemaker-ember-locale-template/pull/1) integrates a `<Note />` component inspired by [ember-styleguide](https://github.com/ember-learn/ember-styleguide/)'s `<EsNote />` that display the informational notes with the mascot's head.
Using `ember-cli-sass` will ease …

Integrate zoey

---

guides/index.md

Fix a typo in `guides/index.md`

Fix a typo in guides/index.md

---

app/components/guidemaker-footer.hbs

Now that we plan to present this project at Ember Fest, it could get more views than just us so it's important we catch-up with the legal part. I asked `@`wifelette the permission to use the logo and the Tomster images. 
She said it's ok and she asked me to write a note in the application footer:
> just write something equivalent [to what the branding page says] in French acknowledging that the logo, Tomster, Zoey, etc. are owned by and used with permission from Tilde Inc and the Ember Project.

Add the permission to use the images in the footer

---

guides/tutorial/part-2/ember-data.md
guides/tutorial/part-2/provider-components.md
guides/tutorial/part-2/route-params.md
guides/tutorial/part-2/service-injection.md

This PR is related to #217: the titles in the recap are the same titles on the different pages of the tutorial. When the recap PR is approved, the final titles should be set and merged.

Align tutorial/part-2 titles with index and recap

---

.local.dic
.remarkignore
guides/models/relationships.md

Closes https://github.com/DazzlingFugu/ember-fr-guides-source/issues/87

Translate guides/models/relationships.md

---

package.json

I hope this PR makes sense to you.
@BlueCutOfficial and @GreatWizard, for your information I have used what is publicly available, I hope this is fine to you.
In any case let me know.
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#people-fields-author-contributors

Add `Mr Chocolatine` to the list of contributors & enrich informations

---

config/environment.js

The public key has been regenerated, so this updates the env config to have the search working.

Update algolia public key

---

.githooks/pre-commit
package.json
scripts/preinstall.mjs

Review one commit at a time highly recommended.
Several improvements for our `pre-commit` git hook:
1. Automatically set up our git hooks custom path 
Continuation of #178, we no longer need to manually run any command.
Things could be better, as always, but for now I have simply assumed all users would execute, at
least, one initial `npm install` when they start working on this repo.
1. The hook now works more efficiently when multiple files are missing from `.remarkignore`.
Now, whatever the number of files not present in `.remarkignore`, the script will display only 
one warning with the list of files that must be added to `.remarkignore`.
1. The hook now automatically adds missing files to `.remarkignore`
The warning has been updated accordingly.
1. The hook now automatically stages …

Refine our `pre-commit` git hook

---

.local.dic
.remarkignore
guides/tutorial/part-1/working-with-data.md
guides/tutorial/part-2/ember-data.md
guides/tutorial/part-2/provider-components.md
guides/tutorial/part-2/route-params.md

Translate guides/tutorial/part-2/ember-data.md

---

.local.dic
.remarkignore
guides/upgrading/index.md

Translate `guides/upgrading/index.md`

---

.local.dic
.remarkignore
guides/code-editors/index.md

Translate `guides/code-editors/index.md`

---

package-lock.json
package.json
scripts/catchup.mjs
scripts/catchup/filesProcessor.mjs
scripts/catchup/gitActions.mjs
scripts/catchup/github.mjs
scripts/catchup/logger.mjs

Relates to #220 (doesn't close it because I consider replacing the argument parser)
This PR implements a new, nicer version of the catchup script:
- The script is split into several files for better readability and maintenance. 
- Multiline messages are returned by dedicated functions to avoid big text blocks in the middle of the logic, making the process easier to follow.
- Additionally, requests to the GitHub API are managed by an instance of a `GithubAdapter` class that can be constructed with all the parameters required for the different requests.
- The possible execution paths have been simplified: the script doesn't make it to the API requests if there's an issue with file writing and never updates `ref-upstream` nor switches back to `master` if there's anything manual to do.
- The …

New nicer version of the catchup script

---

.remarkignore
guides/components/block-content.md
guides/components/introducing-components.md
guides/components/template-tag-format.md
guides/configuring-ember/configuring-ember-cli.md
guides/configuring-ember/debugging.md
guides/configuring-ember/disabling-prototype-extensions.md
guides/configuring-ember/optional-features.md
guides/contributing/index.md
guides/contributing/repositories.md
guides/in-depth-topics/autotracking-in-depth.md
guides/models/relationships.md
guides/routing/defining-your-routes.md
guides/routing/query-params.md
guides/testing/index.md
guides/testing/testing-application.md
guides/testing/testing-components.md
guides/testing/testing-tools.md
guides/tutorial/part-2/service-injection.md
guides/typescript/core-concepts/ember-data.md
guides/typescript/getting-started.md
guides/upgrading/current-edition/tracked-properties.md

PR generated by the catchup script.

Automatic catch up from 5.4 to 5.11

---

.remarkignore
guides/testing/index.md

Translation of /testing/index.md page.

---

guides/configuring-ember/feature-flags.md
guides/configuring-ember/handling-deprecations.md
guides/ember-inspector/deprecations.md
guides/routing/specifying-a-routes-model.md
scripts/catchup.mjs
scripts/catchup/gitActions.mjs

- Run the catchup
- Add the `--no-verify` option on commit (see comment in the code)

feat: automatic catch up from 5.11 to 6.1
