DazzlingFugu/ember-fr-guides-source

guides/release/components/block-content.md

Feat/ translate guides/release/omponents/block-content.md

---

guides/release/accessibility/learning-resources.md

Translations on the learning resources page - Closes #12

feat: translate guides/accessibility/learning-resources.md

---

guides/release/accessibility/testing.md

Translation of the a11y testing readme page

---

guides/release/components/built-in-components.md

Feat/ Translate guides/release/components/built-in-components.md

---

guides/release/accessibility/index.md

Translate Accessibility index page

---

guides/release/accessibility/application-considerations.md
guides/release/pages.yml

Feat: Translate guides/release/accessibility/application-considerations.md

---

.remarkignore
guides/release/applications/index.md

Translate guides/release/applications/index.md

---

.local.dic
.remarkignore
guides/release/accessibility/application-considerations.md
guides/release/accessibility/index.md
guides/release/accessibility/testing.md
guides/release/addons-and-dependencies/index.md
guides/release/components/block-content.md
guides/release/components/built-in-components.md
guides/release/getting-started/quick-start.md

Require #183 to be merged as there are repeated words.

Lint forgotten files

---

.local.dic
.remarkignore
guides/release/tutorial/part-1/index.md

Translate guides/release/tutorial/part-1/index.md

---

.remarkignore
guides/release/accessibility/components.md

Translate a11y components page

---

app/components/guidemaker-footer.hbs
app/components/guidemaker-footer.js
app/instance-initializers/guidemaker-reopener.js
app/styles/app.scss
config/environment.js
package-lock.json
package.json

- Update `guidemaker-ember-locale-template` to get the version with `<GuidemakerFooter />` component provided
- Override `<GuidemakerFooter />` component to adapt it to the needs of the French site
- Reopen `guidemaker` service to add the custom config that is not initially expected by guidemaker ([an issue has been opened](https://github.com/empress/guidemaker/issues/89) in guidemaker repository to get rid of this in the future)

Footer customization

---

.local.dic
.remarkignore
guides/services/index.md

feat: translate guides/services/index.md

---

guides/code-editors/index.md
guides/components/helper-functions.md
guides/in-depth-topics/patterns-for-components.md
guides/in-depth-topics/rendering-values.md
guides/models/finding-records.md
guides/models/relationships.md
guides/routing/query-params.md
guides/routing/redirection.md
guides/routing/specifying-a-routes-model.md

Update the English files to Ember 5.1.0 docs. We have been lucky this time, no change on the files that are already translated.

Catchup 5.1.0

---

.local.dic
.remarkignore
guides/tutorial/part-1/orientation.md

Translate guides/tutorial/part-1/orientation.md

---

.local.dic
.remarkignore
guides/tutorial/part-1/automated-testing.md
guides/tutorial/part-1/building-pages.md

Translate guides/tutorial/part-1/automated-testing

---

.local.dic
.remarkignore
guides/applications/ember-engines.md

Translate guides/applications/ember-engines.md

---

.local.dic
.remarkignore
guides/tutorial/part-1/building-pages.md
guides/tutorial/part-1/component-basics.md

Translate guides/tutorial/part-1/component-basics

---

guides/applications/initializers.md

This translation is still in progress, but I would like to merge all the translated work into `master` in order to make some tests with a translation service. That's why I open and merge a PR for a WIP file.

Start translating guides/applications/initializers.md

---

.local.dic
.remarkignore
guides/tutorial/part-1/interactive-components.md
guides/tutorial/part-1/more-about-components.md
guides/tutorial/part-1/recap.md
guides/tutorial/part-1/reusable-components.md
guides/tutorial/part-1/working-with-data.md
guides/tutorial/part-2/ember-data.md
guides/tutorial/part-2/provider-components.md
guides/tutorial/part-2/recap.md
guides/tutorial/part-2/route-params.md
guides/tutorial/part-2/service-injection.md

Closes #142
Closes #143 
Closes #144 
Closes #146 
Closes #147 
This PR is a bit tough because I tested the usage of Crowdin to speed up the translation on the whole `tutorial/part-1` folder. There are also a couple of changes in `tutorial/part-2` because the same working data are reused so it will be simpler to keep everything aligned.

Translate guides/tutorial/part-1

---

guides/routing/index.md

Translate `guides/routing/index.md` to French

---

.local.dic
.remarkignore
guides/tutorial/part-2/index.md

Translate guides/tutorial/part-2/index.md

---

.local.dic
guides/models/finding-records.md

Closes [#74](https://github.com/DazzlingFugu/ember-fr-guides-source/issues/74)

Translate guides/release/models/finding-records.md

---

.remarkignore
guides/tutorial/part-2/recap.md

Translate guides/tutorial/part-2/recap.md

---

.remarkignore

Oversight from pull request #210 .
Linked to #66.

Add `guides/routing/index.md` to `.remarkignore`

---

guides/addons-and-dependencies/index.md

Translate guides/addons-and-dependencies/index from 5.1 to 5.4

---

app/index.html

Related to #192 but there's much to do.

Set HTML page main language to fr 

---

.local.dic
.remarkignore
guides/configuring-ember/build-targets.md

Translate `guides/configuring-ember/build-targets.md` to French

---

.local.dic
CONTRIBUTING.md
package.json
scripts/lint:fix:local-dic.mjs

Create a script to sort `.local.dic` file.
The logic follows what was done in #225 .
Resolves #226
Resolves #230

feat: create a script to sort `.local.dic` file

---

.remarkignore
guides/applications/initializers.md

Translate guides/applications/initializers.md

---

.remarkignore
guides/models/creating-updating-and-deleting-records.md

Supersedes #211 .
Resolves #95 .
---
Review one commit at a time.
I have decided to not make a single-commit PR to better track/understand this PR actually replaces an existing one.

Translate `guides/models/creating-updating-and-deleting-records.md` to French

---

guides/accessibility/components.md

Translate `guides/accessibility/components` to 5.5

---

.remarkignore
guides/components/block-content.md
guides/components/looping-through-lists.md

Translate `guides/components/looping-through-lists.md`

---

.local.dic
.remarkignore
guides/applications/run-loop.md

Translate `guides/applications/run-loop.md`

---

.local.dic
.remarkignore
guides/components/component-arguments-and-html-attributes.md

Translate `guides/components/components-arguments-and-html-attributes.md`

---

.remarkignore
guides/components/block-content.md
guides/components/index.md

Translate `guides/components/index.md`

---

.remarkignore
guides/tutorial/part-1/more-about-components.md
guides/tutorial/part-1/reusable-components.md
guides/tutorial/part-1/working-with-data.md
guides/tutorial/part-2/route-params.md

Translate `guides/tutorial/part-2/route-params`

---

.local.dic
guides/code-editors/index.md

Translate `/code-editors/index.md`- 5.4 to 6.1
